/* Capacity Engine */

class Capacity {
    constructor() {
    }

    /**
     * Calculates the expanded capacity by expanding the date ranges in capacity.entries
     * based on the selected granularity (month, week, quarter).
     * @param {Object} plan - The plan data model
     * @returns {Array} Array of expanded capacity objects e.g., [{ period: '2026-Jan', capacity: 40 }]
     */
    calculateExpandedCapacity(plan) {
        if (!plan || !plan.capacity || !plan.capacity.entries || plan.capacity.entries.length === 0) {
            return [];
        }

        const granularity = plan.capacity.granularity || 'month';
        const entries = plan.capacity.entries;

        // Group capacity by period
        const expandedMap = new Map();

        entries.forEach(entry => {
            const startParts = entry.startDate.split('-');
            const endParts = entry.endDate.split('-');

            if (startParts.length !== 3 || endParts.length !== 3) return;

            // Instantiate dates correctly to avoid UTC offset issues
            const startDate = new Date(startParts[0], startParts[1] - 1, startParts[2]);
            const endDate = new Date(endParts[0], endParts[1] - 1, endParts[2]);

            if (isNaN(startDate) || isNaN(endDate) || startDate > endDate) return;

            // Iterate over each day in the range and group by the selected granularity
            let currentDate = new Date(startDate);
            while (currentDate <= endDate) {
                const periodKey = this.getPeriodKey(currentDate, granularity);

                // We assume the entry's capacity represents the capacity *per period* (e.g., 40 per month).
                // If multiple entries overlap the same period, we'll keep the highest capacity defined,
                // or you could add them depending on business rules. The requirements imply a single capacity
                // value per period defined by the ranges. We'll set the value.
                if (!expandedMap.has(periodKey)) {
                    expandedMap.set(periodKey, entry.capacity);
                } else {
                    // If ranges overlap and have different values, take max or sum?
                    // Let's assume standard behavior is to take the most recent/max or they shouldn't overlap.
                    expandedMap.set(periodKey, Math.max(expandedMap.get(periodKey), entry.capacity));
                }

                // Advance by 1 day
                currentDate.setDate(currentDate.getDate() + 1);
            }
        });

        // Convert map to sorted array
        const result = [];
        for (const [period, capacity] of expandedMap.entries()) {
            result.push({ period, capacity });
        }

        // Sort by period (since period keys are designed to be sortable e.g. "2026-01" or "2026-W01")
        result.sort((a, b) => a.period.localeCompare(b.period));

        return result;
    }

    /**
     * Calculates the demand generated by tasks across defined periods.
     * @param {Object} plan - The plan data model
     * @returns {Array} Array of demand objects e.g., [{ period: '2026-01', demand: 22 }]
     */
    calculateDemand(plan) {
        if (!plan || !plan.tasks || plan.tasks.length === 0) {
            return [];
        }

        const granularity = (plan.capacity && plan.capacity.granularity) ? plan.capacity.granularity : 'month';
        const adjustmentPercent = plan.demandAdjustmentPercent !== undefined ? plan.demandAdjustmentPercent : 0;
        const adjustmentFactor = 1 - (adjustmentPercent / 100);

        const demandMap = new Map();

        plan.tasks.forEach(task => {
            if (!task.startDate || !task.endDate) return;

            const startParts = task.startDate.split('-');
            const endParts = task.endDate.split('-');
            if (startParts.length !== 3 || endParts.length !== 3) return;

            const startDate = new Date(startParts[0], startParts[1] - 1, startParts[2]);
            const endDate = new Date(endParts[0], endParts[1] - 1, endParts[2]);

            if (isNaN(startDate) || isNaN(endDate) || startDate > endDate) return;

            const effort = task.effort || { design: 0, dev: 0, test: 0 };
            const totalEffort = (effort.design || 0) + (effort.dev || 0) + (effort.test || 0);

            if (totalEffort <= 0) return;

            // Calculate number of working days (weekdays)
            let workingDays = 0;
            let current = new Date(startDate);
            while (current <= endDate) {
                const dayOfWeek = current.getDay();
                if (dayOfWeek !== 0 && dayOfWeek !== 6) { // 0 = Sunday, 6 = Saturday
                    workingDays++;
                }
                current.setDate(current.getDate() + 1);
            }

            if (workingDays === 0) return; // Task is entirely on weekends

            const effortPerDay = totalEffort / workingDays;

            // Distribute effort across working days
            current = new Date(startDate);
            while (current <= endDate) {
                const dayOfWeek = current.getDay();
                if (dayOfWeek !== 0 && dayOfWeek !== 6) {
                    const periodKey = this.getPeriodKey(current, granularity);
                    const existingDemand = demandMap.get(periodKey) || 0;
                    demandMap.set(periodKey, existingDemand + effortPerDay);
                }
                current.setDate(current.getDate() + 1);
            }
        });

        // Apply adjustment factor and format output
        const result = [];
        for (const [period, rawDemand] of demandMap.entries()) {
            const adjustedDemand = rawDemand * adjustmentFactor;
            result.push({ period, demand: adjustedDemand });
        }

        // Sort by period
        result.sort((a, b) => a.period.localeCompare(b.period));

        return result;
    }

    /**
     * Generates a unique, sortable string key for a date based on the granularity.
     */
    getPeriodKey(date, granularity) {
        const year = date.getFullYear();
        const month = date.getMonth(); // 0-11
        const monthStr = String(month + 1).padStart(2, '0');

        if (granularity === 'month') {
            return `${year}-${monthStr}`; // e.g. 2026-01
        } else if (granularity === 'quarter') {
            const quarter = Math.floor(month / 3) + 1;
            return `${year}-Q${quarter}`; // e.g. 2026-Q1
        } else if (granularity === 'week') {
            // ISO week date calculation
            const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
            const dayNum = d.getUTCDay() || 7;
            d.setUTCDate(d.getUTCDate() + 4 - dayNum);
            const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
            const weekNo = Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
            const weekStr = String(weekNo).padStart(2, '0');
            return `${d.getUTCFullYear()}-W${weekStr}`; // e.g. 2026-W01
        }

        return `${year}-${monthStr}`; // fallback to month
    }
}