[pytest]
addopts = --html=report.html --self-contained-html --tracing=retain-on-failure --screenshot=only-on-failure -v
testpaths = tests
python_files = *_test.py
python_classes = Test*
python_functions = test_*

[playwright]
browser = chromium
